name: sms_spam_detection
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  telephony: ^0.2.0
  http: ^0.13.6
  sqflite: ^2.2.8+2
  path: ^1.8.2
  sqflite_common_ffi: ^2.2.5
  sqlite3_flutter_libs: ^0.5.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true